version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: scontrini-app-per-scontrini_web_1
      APP_PORT: 8080

  web:
    image: app-per-scontrini:1.2.0-local
    pull_policy: never
    restart: on-failure
    volumes:
      - "${APP_DATA_DIR}/data:/data"
